version: '3.8'

services:
  db:
    container_name: event-container
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    ports:
      - 5468:${TYPEORM_PORT}
